version: '3.7'
#networks:
#  kong-net:
#    driver: bridge
#######################################
# Kong: The API Gateway
#######################################
services:
  kong:
    image: kong_nodb:latest
    restart: on-failure
    container_name: kong_nodb
    #networks:
    #  - kong-net
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: kong.yaml
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ACCESS_LOG: /dev/stdout
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 5s
      timeout: 2s
      retries: 15
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8443:8443"
      - "8444:8444"

  #######################################
  # Konga prepare
  #######################################
  konga-prepare:
    image: pantsel/konga:latest
    container_name: konga-prepare
    networks:
      - kong-net
    restart: on-failure
  #######################################
  # Konga: Kong GUI
  #######################################
  konga:
    image: pantsel/konga:latest
    container_name: konga
    restart: always
    networks:
      - kong-net
    environment:
      NODE_ENV: production
      DB_HOST: kong-database
    healthcheck:
      test: ["CMD", "kong", "health"]
    depends_on:
      - konga-prepare
    ports:
      - "1337:1337"