kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: kong
  namespace: {{namespace}}
  labels:
    team: plattformsikkerhet
spec:
  image: {{image}}
  ingresses:
  {{#each ingresses}}
     - "{{this}}"
    {{/each}}
  liveness:
    path: /status
    initialDelay: 10
    periodSeconds: 10
    failureThreshold: 30
    port: 8001
  readiness:
    path: /status
    initialDelay: 10
    periodSeconds: 10
    failureThreshold: 30
    port: 8001
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 900m
      memory: 2Gi
    requests:
      cpu: 900m
      memory: 2Gi
  prometheus:
    enabled: true
    path: /metrics
    port: "8001"
  cpuThresholdPercentage: 80
  port: 8000
  env:
  {{#each envs}}
    - "{{this.name}}"
      "{{this.value}}"
    {{/each}}