kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: kong
  namespace: {{namespace}}
  labels:
    team: plattformsikkerhet
spec:
  image: {{image}}
  ingresses:
  {{#each ingresses}}
     - "{{this}}"
    {{/each}}
  liveness:
    path: /status
    initialDelay: 10
    periodSeconds: 10
    failureThreshold: 30
    port: {{admin-port}}
  readiness:
    path: /status
    initialDelay: 10
    periodSeconds: 10
    failureThreshold: 30
    port: {{admin-port}}
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 900m
      memory: 2Gi
    requests:
      cpu: 900m
      memory: 2Gi
  prometheus:
    enabled: true
    path: /metrics
    port: "{{admin-port}}"
  cpuThresholdPercentage: 80
  port: {{proxy-port}}
  env:
  {{#each envs}}
    - name: "{{this.name}}"
      value: "{{this.value}}"
    {{/each}}